openapi: 3.0.0
info:
  title: Sukrat Lodge API Swagger
  description: Sukrat Lodge API documentation
  version: '1.0'
  x-logo:
    url: https://github.com/joolfe/logoBanner.png
    backgroundColor: '#FFFFFF'
    altText: logo
  termsOfService: '#'
  contact:
    name: Mero Vision
    url: https://merovision.com
    email: merovision720@gmail.com
  license:
    name: MIT
    url: https://es.wikipedia.org/wiki/Licencia_MIT
servers:
  - url: https://admin.sukrathotel.net/
    description: server
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
tags:
  - name: Authentication
  - name: Floor Plan
  - name: Room
  - name: Room Type
  - name: Room Amenity
  - name: Booking
paths:
  /api/admin/login:
    post:
      tags:
        - Authentication
      summary: login
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: alexxy@hamham.uk
                password:
                  type: string
                  example: P@ssw0rd
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/admin/floor-plan:
    post:
      tags:
        - Floor Plan
      summary: store floor plan
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                title: Ground Floor41
                description: Text
                room_id:
                  - 1
                  - 2
                  - 3
                  - 5
      security:
        - bearerAuth: []
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: branch-id
          in: header
          schema:
            type: integer
          example: '1'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - Floor Plan
      summary: show all floor plans
      security:
        - bearerAuth: []
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: branch-id
          in: header
          schema:
            type: integer
          example: '10'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/admin/floor-plan/7:
    post:
      tags:
        - Floor Plan
      summary: update floor plan
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                title:
                  type: string
                  example: Ground77
                description:
                  type: string
                  example: hy
                room_id:
                  type: string
                  example: '[1,2]'
                _method:
                  type: string
                  example: PUT
      security:
        - bearerAuth: []
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: branch-id
          in: header
          schema:
            type: integer
          example: '10'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/admin/rooms:
    post:
      tags:
        - Room
      summary: store room
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                title:
                  type: string
                  example: T3
                description:
                  type: string
      security:
        - bearerAuth: []
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: branch-id
          in: header
          schema:
            type: integer
          example: '1'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - Room
      summary: show all rooms
      security:
        - bearerAuth: []
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: branch-id
          in: header
          schema:
            type: integer
          example: '10'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/admin/room-type:
    post:
      tags:
        - Room Type
      summary: store room type
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                title: Deluxe Suite 2
                description: Spacious suite with ocean view
                max_occupancy: 4
                no_of_adult: 2
                no_of_child: 2
                base_price: 299.99
                discount_type: percentage
                discount: 10
                room_id:
                  - 1
                  - 2
                amenity_id:
                  - 1
                  - 2
      security:
        - bearerAuth: []
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: branch-id
          in: header
          schema:
            type: integer
          example: '1'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - Room Type
      summary: show all room type
      security:
        - bearerAuth: []
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: branch-id
          in: header
          schema:
            type: integer
          example: '1'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/admin/room-type/{id}:
    post:
      tags:
        - Room Type
      summary: update room type
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                title: Deluxe Suite 2
                description: Spacious suite with ocean view
                max_occupancy: 4
                no_of_adult: 2
                no_of_child: 2
                base_price: 299.99
                discount_type: percentage
                discount: 10
                room_id:
                  - 1
                  - 2
                amenity_id:
                  - 1
                  - 2
                _method: put
      security:
        - bearerAuth: []
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: branch-id
          in: header
          schema:
            type: integer
          example: '1'
        - name: id
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - Room Type
      summary: delete room type
      security:
        - bearerAuth: []
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: branch-id
          in: header
          schema:
            type: integer
          example: '1'
        - name: id
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/admin/room-amenity:
    post:
      tags:
        - Room Amenity
      summary: store room amenity
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                amenity_name:
                  type: string
                  example: House Keeping
                description:
                  type: string
      security:
        - bearerAuth: []
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: branch-id
          in: header
          schema:
            type: integer
          example: '1'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - Room Amenity
      summary: show all room amenity
      security:
        - bearerAuth: []
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: branch-id
          in: header
          schema:
            type: integer
          example: '1'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/admin/booking/search/available-rooms:
    get:
      tags:
        - Booking
      summary: search availlable rooms
      security:
        - bearerAuth: []
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: branch-id
          in: header
          schema:
            type: integer
          example: '1'
        - name: check_in
          in: query
          schema:
            type: string
          example: '2025-02-12'
        - name: check_out
          in: query
          schema:
            type: string
          example: '2025-04-23'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/admin/booking:
    post:
      tags:
        - Booking
      summary: store booking
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                check_in:
                  type: string
                  example: '2025-04-13'
                check_out:
                  type: string
                  example: '2025-04-14'
                name:
                  type: string
                  example: John Doe
                email:
                  type: string
                  example: john@example.com
                phone:
                  type: integer
                  example: '9800000000'
                city:
                  type: string
                  example: Kathmandu
                country:
                  type: string
                  example: Nepal
                gender:
                  type: string
                  example: Male
                no_of_adult:
                  type: integer
                  example: '2'
                no_of_child:
                  type: integer
                  example: '1'
                booking_room_price:
                  type: integer
                  example: '5000'
                additional_amount:
                  type: integer
                  example: '1000'
                discount:
                  type: integer
                  example: '500'
                tax:
                  type: integer
                  example: '13'
                documents[0][document_title]:
                  type: string
                  example: Citizenship
                documents[0][image]:
                  type: string
                  format: binary
                booking_details[0][room_id]:
                  type: integer
                  example: '1'
                booking_details[0][allocated_price]:
                  type: integer
                  example: '200'
                booking_details[0][guests]:
                  type: integer
                  example: '2'
                booking_details[0][instructions]:
                  type: string
                  example: Near elevator
      security:
        - bearerAuth: []
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: branch-id
          in: header
          schema:
            type: integer
          example: '1'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
